name: Fix Code Style

on:
  pull_request:
    branches:
      - main
      - development

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pint

      - name: Run Pint
        run: pint

      - name: Configure Git
        run: |
          git config user.name "ramalho7"
          git config user.email "adryelll85@gmail.com"

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Apply automatic changes - pint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
